name: CI-CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Pipeline
        run: echo "Hello Seethareddy! CI/CD Works"
